export enum ContextMenuActionType {
    SHOW_CONTEXT_MENU = 'SHOW_CONTEXT_MENU',
    CLOSE_CONTEXT_MENU = 'CLOSE_CONTEXT_MENU',
    OVERLAP_CONTEXT_MENU = 'OVERLAP_CONTEXT_MENU',
    PARAMETERS_FIELD_CLICK = 'PARAMETERS_FIELD_CLICK',
    CANCELING_PARAMETER = 'CANCELING_PARAMETER',

    CHANGE_BLOCK_COLOR = 'CHANGE_BLOCK_COLOR',

}