export enum BlocksActionTypes {
    FETCH_ORIGIN_BLOCKS_SUCCESS = "FETCH_ORIGIN_BLOCKS_SUCCESS",
    FETCH_BLOCKS = 'FETCH_BLOCKS',
    FETCH_BLOCKS_SUCCESS = 'FETCH_BLOCKS_SUCCESS',
    FETCH_BLOCKS_ERROR = 'FETCH_BLOCKS_ERROR',
    ADD_BLOCK = 'ADD_BLOCK',
    PUT_DATA = 'PUT_DATA',
    CREATE_CONNECTION = 'CREATE_CONNECTION',
    UPDATE_BLOCKS = 'UPDATE_BLOCKS'
}