export enum BlocksActionTypes {
    FETCH_ORIGIN_BLOCKS_SUCCESS = "FETCH_ORIGIN_BLOCKS_SUCCESS",
    FETCH_BLOCKS = 'FETCH_BLOCKS',
    FETCH_BLOCKS_SUCCESS = 'FETCH_BLOCKS_SUCCESS',
    FETCH_BLOCKS_ERROR = 'FETCH_BLOCKS_ERROR',
    ADD_BLOCK = 'ADD_BLOCK'
}