export const CHOICE_PARAMETER_TYPE = "Тип"
export const NAME_PARAMETER = "Имя"
export const VALUE_PARAMETER = "Значение"
export const LABEL_BUTTONBLOCK = "Принять"
export const EDIT_BUTTONBLOCK = "Редактировать"
